version: 8.15.0-c0a6b373-SNAPSHOT



#image:
#  registry: docker.elastic.co/observability-ci/moxy
#apm_ingest_service_host: apm-ingest-service
#local_project:
#  elasticsearch:
#    url: http://elasticsearch-es-http:9200
#    username: admin
#    password: changeme
#  kibana:
#    url: http://kibana-kb-http:5601
#
#log_level: info
#moxy_es_stub: "false"
#moxy_index_latency: 0s
