// Code generated by "modelgen". DO NOT EDIT.
package model

import (
	"time"

	"github.com/elastic/apm-server/model/modelpb"
)

type Metadata struct {
	mixinMetadata
	pb        modelpb.Metadata
	Service   Service
	Process   Process
	System    System
	User      User
	UserAgent UserAgent
	Client    Client
	Cloud     Cloud
}

type Service struct {
	pb        modelpb.Service
	Language  Language
	Runtime   Runtime
	Framework Framework
	Agent     Agent
	Node      ServiceNode
}

type Language struct {
	pb modelpb.Language
}

type Runtime struct {
	pb modelpb.Runtime
}

type Framework struct {
	pb modelpb.Framework
}

type Agent struct {
	pb modelpb.Agent
}

type ServiceNode struct {
	pb modelpb.ServiceNode
}

type Process struct {
	pb   modelpb.Process
	Argv []string
}

type System struct {
	pb         modelpb.System
	Container  Container
	Kubernetes Kubernetes
}

type Container struct {
	pb modelpb.Container
}

type Kubernetes struct {
	pb   modelpb.Kubernetes
	Node KubernetesNode
	Pod  KubernetesPod
}

type KubernetesNode struct {
	pb modelpb.KubernetesNode
}

type KubernetesPod struct {
	pb modelpb.KubernetesPod
}

type User struct {
	pb modelpb.User
}

type UserAgent struct {
	pb modelpb.UserAgent
}

type Client struct {
	pb modelpb.Client
}

type Cloud struct {
	pb      modelpb.Cloud
	Account CloudAccount
}

type CloudAccount struct {
	pb modelpb.CloudAccount
}

// Transaction foo bar
type Transaction struct {
	pb        modelpb.Transaction
	Metadata  Metadata
	Timestamp time.Time
	Duration  time.Time
	Context   TransactionContext
}

type TransactionContext struct {
	mixinTransactionContext
	pb modelpb.TransactionContext
}
