// Code generated by "modelgen". DO NOT EDIT.
package model

import (
	"time"

	"github.com/elastic/apm-server/model/modelpb"
)

type Labels struct {
	Labels map[string]LabelValue
}

// LabelValue holds a label value.
type LabelValue struct {
	Value isLabelValue_Value
}

type Metadata struct {
	Service   Service
	Process   Process
	System    System
	User      User
	UserAgent UserAgent
	Client    Client
	Cloud     Cloud
	Labels    map[string]LabelValue
}

type Service struct {
	Name        string
	Version     string
	Environment string
	Language    Language
	Runtime     Runtime
	Framework   Framework
	Agent       Agent
	Node        ServiceNode
}

type Language struct {
	Name    string
	Version string
}

type Runtime struct {
	Name    string
	Version string
}

type Framework struct {
	Name    string
	Version string
}

type Agent struct {
	Name        string
	Version     string
	EphemeralId string
}

type ServiceNode struct {
	Name string
}

type Process struct {
	Pid   int64
	Ppid  int64
	Title string
	Argv  []string
}

type System struct {
	DetectedHostname   string
	ConfiguredHostname string
	Architecture       string
	IP                 string
	Container          Container
	Kubernetes         Kubernetes
}

type Container struct {
	Id string
}

type Kubernetes struct {
	Namespace string
	Node      KubernetesNode
	Pod       KubernetesPod
}

type KubernetesNode struct {
	Name string
}

type KubernetesPod struct {
	Name string
	Uid  string
}

type User struct {
	Id     string
	Email  string
	Name   string
	Domain string
}

type UserAgent struct {
	Original string
	Name     string
}

type Client struct {
	IP string
}

type Cloud struct {
	Account          CloudAccount
	AvailabilityZone string
}

type CloudAccount struct {
	Id   string
	Name string
}

type Transaction struct {
	Metadata            Metadata
	Type                string
	Name                string
	Result              string
	Outcome             string
	ID                  string
	TraceID             string
	ParentID            string
	Timestamp           time.Time
	Duration            time.Time
	Sampled             bool
	RepresentativeCount float64
	Context             TransactionContext
}

type TransactionContext struct {
	Custom       types.Struct
	Experimental types.Value
}
