apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: default
spec:
  version: 8.8.0-56b80d12-SNAPSHOT
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      http:
        tls:
          selfSignedCertificate:
            disabled: true
      containers:
      - name: apm-server
        resources:
          limits:
            cpu: 1
            memory: "2Gi"
          requests:
            cpu: 1
            memory: "1Gi"
