---
name: Label checks
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check labels
        run: cd ./.github/actions/check_labels/main.go && go run .
