// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apm-server/model/proto/metricset.proto

package modelpb

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Metricset struct {
	Metadata                  `protobuf:"bytes,1,opt,name=metadata,proto3,embedded=metadata" json:"metadata"`
	Timestamp                 time.Time `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"@timestamp"`
	Name                      string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TimeseriesId              string    `protobuf:"bytes,4,opt,name=timeseries_id,json=timeseriesId,proto3" json:"timeseries_id,omitempty"`
	EventOutcome              string    `protobuf:"bytes,5,opt,name=event_outcome,json=eventOutcome,proto3" json:"event_outcome,omitempty"`
	TransactionName           string    `protobuf:"bytes,6,opt,name=transaction_name,json=transactionName,proto3" json:"transaction_name,omitempty"`
	TransactionType           string    `protobuf:"bytes,7,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	TransactionResult         string    `protobuf:"bytes,8,opt,name=transaction_result,json=transactionResult,proto3" json:"transaction_result,omitempty"`
	TransactionRoot           bool      `protobuf:"varint,9,opt,name=transaction_root,json=transactionRoot,proto3" json:"transaction_root,omitempty"`
	SpanType                  string    `protobuf:"bytes,10,opt,name=span_type,json=spanType,proto3" json:"span_type,omitempty"`
	SpanSubtype               string    `protobuf:"bytes,11,opt,name=span_subtype,json=spanSubtype,proto3" json:"span_subtype,omitempty"`
	DesinationServiceResource string    `protobuf:"bytes,12,opt,name=desination_service_resource,json=desinationServiceResource,proto3" json:"desination_service_resource,omitempty"`
	Metrics                   []*Metric `protobuf:"bytes,13,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (m *Metricset) Reset()         { *m = Metricset{} }
func (m *Metricset) String() string { return proto.CompactTextString(m) }
func (*Metricset) ProtoMessage()    {}
func (*Metricset) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad18946aa86de2d, []int{0}
}
func (m *Metricset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metricset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metricset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metricset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metricset.Merge(m, src)
}
func (m *Metricset) XXX_Size() int {
	return m.Size()
}
func (m *Metricset) XXX_DiscardUnknown() {
	xxx_messageInfo_Metricset.DiscardUnknown(m)
}

var xxx_messageInfo_Metricset proto.InternalMessageInfo

func (m *Metricset) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *Metricset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metricset) GetTimeseriesId() string {
	if m != nil {
		return m.TimeseriesId
	}
	return ""
}

func (m *Metricset) GetEventOutcome() string {
	if m != nil {
		return m.EventOutcome
	}
	return ""
}

func (m *Metricset) GetTransactionName() string {
	if m != nil {
		return m.TransactionName
	}
	return ""
}

func (m *Metricset) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *Metricset) GetTransactionResult() string {
	if m != nil {
		return m.TransactionResult
	}
	return ""
}

func (m *Metricset) GetTransactionRoot() bool {
	if m != nil {
		return m.TransactionRoot
	}
	return false
}

func (m *Metricset) GetSpanType() string {
	if m != nil {
		return m.SpanType
	}
	return ""
}

func (m *Metricset) GetSpanSubtype() string {
	if m != nil {
		return m.SpanSubtype
	}
	return ""
}

func (m *Metricset) GetDesinationServiceResource() string {
	if m != nil {
		return m.DesinationServiceResource
	}
	return ""
}

func (m *Metricset) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Metric_Double
	//	*Metric_Histogram
	Value isMetric_Value `protobuf_oneof:"value"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad18946aa86de2d, []int{1}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return m.Size()
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

type isMetric_Value interface {
	isMetric_Value()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Metric_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof" json:"double,omitempty"`
}
type Metric_Histogram struct {
	Histogram *MetricHistogram `protobuf:"bytes,5,opt,name=histogram,proto3,oneof" json:"histogram,omitempty"`
}

func (*Metric_Double) isMetric_Value()    {}
func (*Metric_Histogram) isMetric_Value() {}

func (m *Metric) GetValue() isMetric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Metric) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Metric) GetDouble() float64 {
	if x, ok := m.GetValue().(*Metric_Double); ok {
		return x.Double
	}
	return 0
}

func (m *Metric) GetHistogram() *MetricHistogram {
	if x, ok := m.GetValue().(*Metric_Histogram); ok {
		return x.Histogram
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metric_Double)(nil),
		(*Metric_Histogram)(nil),
	}
}

type MetricHistogram struct {
	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Counts []float64 `protobuf:"fixed64,2,rep,packed,name=counts,proto3" json:"counts,omitempty"`
}

func (m *MetricHistogram) Reset()         { *m = MetricHistogram{} }
func (m *MetricHistogram) String() string { return proto.CompactTextString(m) }
func (*MetricHistogram) ProtoMessage()    {}
func (*MetricHistogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_bad18946aa86de2d, []int{2}
}
func (m *MetricHistogram) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricHistogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricHistogram.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricHistogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricHistogram.Merge(m, src)
}
func (m *MetricHistogram) XXX_Size() int {
	return m.Size()
}
func (m *MetricHistogram) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricHistogram.DiscardUnknown(m)
}

var xxx_messageInfo_MetricHistogram proto.InternalMessageInfo

func (m *MetricHistogram) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *MetricHistogram) GetCounts() []float64 {
	if m != nil {
		return m.Counts
	}
	return nil
}

func init() {
	proto.RegisterType((*Metricset)(nil), "elastic.apm.model.Metricset")
	proto.RegisterType((*Metric)(nil), "elastic.apm.model.Metric")
	proto.RegisterType((*MetricHistogram)(nil), "elastic.apm.model.MetricHistogram")
}

func init() {
	proto.RegisterFile("apm-server/model/proto/metricset.proto", fileDescriptor_bad18946aa86de2d)
}

var fileDescriptor_bad18946aa86de2d = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xad, 0x36, 0x4d, 0x63, 0xa5, 0xa5, 0xab, 0x0e, 0x45, 0x6d, 0xc1, 0xc9, 0x32, 0x36,
	0x32, 0x46, 0x6d, 0x68, 0xef, 0x63, 0x0d, 0x0c, 0xba, 0x43, 0xb7, 0xe1, 0xf6, 0xb4, 0x4b, 0x90,
	0x6d, 0xcd, 0x15, 0xd8, 0x96, 0xb1, 0xe4, 0x40, 0xbf, 0x45, 0xbf, 0xc7, 0xbe, 0x48, 0x8f, 0x39,
	0xee, 0x94, 0x8d, 0xe4, 0xb6, 0x4f, 0x31, 0xfc, 0x64, 0x27, 0x59, 0xb3, 0x5e, 0x84, 0xde, 0xff,
	0xfd, 0xde, 0x7b, 0x7f, 0x78, 0x12, 0x7e, 0xc3, 0xf2, 0xf4, 0x4c, 0xf1, 0x62, 0xc2, 0x0b, 0x2f,
	0x95, 0x11, 0x4f, 0xbc, 0xbc, 0x90, 0x5a, 0x7a, 0x29, 0xd7, 0x85, 0x08, 0x15, 0xd7, 0x2e, 0xc4,
	0xe4, 0x90, 0x27, 0x4c, 0x69, 0x11, 0xba, 0x2c, 0x4f, 0x5d, 0x00, 0x4f, 0x5e, 0x3f, 0x5f, 0xca,
	0x22, 0xa6, 0x99, 0xa9, 0x3c, 0xe9, 0xc5, 0x52, 0xc6, 0x09, 0x37, 0xc9, 0xa0, 0xfc, 0xee, 0x69,
	0x91, 0x72, 0xa5, 0x59, 0x9a, 0xd7, 0xc0, 0x59, 0x2c, 0xf4, 0x5d, 0x19, 0xb8, 0xa1, 0x4c, 0xbd,
	0x58, 0xc6, 0x72, 0x45, 0x56, 0x91, 0xe9, 0x59, 0xdd, 0x0c, 0x3e, 0x58, 0xb4, 0xb0, 0x7d, 0xdd,
	0xb8, 0x23, 0x97, 0xb8, 0xd3, 0xcc, 0xa3, 0xa8, 0x8f, 0x86, 0xdd, 0xf3, 0x53, 0x77, 0xc3, 0xaa,
	0x7b, 0x5d, 0x23, 0xa3, 0xce, 0xe3, 0xac, 0x67, 0x4d, 0x67, 0x3d, 0xe4, 0x2f, 0xcb, 0xc8, 0x57,
	0x6c, 0x2f, 0x2d, 0xd1, 0x2d, 0xe8, 0x71, 0xe2, 0x1a, 0xd3, 0x6e, 0x63, 0xc5, 0xbd, 0x6d, 0x88,
	0xd1, 0x51, 0xd5, 0xe2, 0xcf, 0xac, 0x87, 0x3f, 0x2c, 0xab, 0x1e, 0x7e, 0xf5, 0x90, 0xbf, 0x6a,
	0x42, 0x08, 0x6e, 0x65, 0x2c, 0xe5, 0x74, 0xbb, 0x8f, 0x86, 0xb6, 0x0f, 0x77, 0xf2, 0x0a, 0xef,
	0x03, 0xc0, 0x0b, 0xc1, 0xd5, 0x58, 0x44, 0xb4, 0x05, 0xc9, 0xbd, 0x95, 0xf8, 0x29, 0xaa, 0x20,
	0x3e, 0xe1, 0x99, 0x1e, 0xcb, 0x52, 0x87, 0x32, 0xe5, 0x74, 0xc7, 0x40, 0x20, 0x7e, 0x31, 0x1a,
	0x79, 0x8b, 0x5f, 0xe8, 0x82, 0x65, 0x8a, 0x85, 0x5a, 0xc8, 0x6c, 0x0c, 0x93, 0xda, 0xc0, 0x1d,
	0xac, 0xe9, 0x9f, 0xd9, 0x26, 0xaa, 0xef, 0x73, 0x4e, 0x77, 0x37, 0xd0, 0xdb, 0xfb, 0x9c, 0x93,
	0x33, 0x4c, 0xd6, 0xd1, 0x82, 0xab, 0x32, 0xd1, 0xb4, 0x03, 0xf0, 0xe1, 0x5a, 0xc6, 0x87, 0xc4,
	0xd3, 0xce, 0x85, 0x94, 0x9a, 0xda, 0x7d, 0x34, 0xec, 0xfc, 0xd3, 0xd9, 0x97, 0x52, 0x93, 0x53,
	0x6c, 0xab, 0x9c, 0xd5, 0xd3, 0x31, 0x34, 0xec, 0x54, 0x02, 0x8c, 0x7d, 0x89, 0xf7, 0x20, 0xa9,
	0xca, 0x00, 0xf2, 0x5d, 0xc8, 0x77, 0x2b, 0xed, 0xc6, 0x48, 0xe4, 0x3d, 0x3e, 0x8d, 0xb8, 0x12,
	0x19, 0x83, 0x49, 0xd5, 0x83, 0x13, 0x21, 0xaf, 0x0c, 0xca, 0xb2, 0x08, 0x39, 0xdd, 0x83, 0x8a,
	0xe3, 0x15, 0x72, 0x63, 0x08, 0xbf, 0x06, 0xc8, 0x05, 0xde, 0xad, 0x5f, 0x33, 0xdd, 0xef, 0x6f,
	0x0f, 0xbb, 0xe7, 0xc7, 0xff, 0x7f, 0x21, 0x85, 0x08, 0xfd, 0x86, 0x1c, 0xfc, 0x40, 0xb8, 0x6d,
	0xb4, 0xe5, 0x36, 0xd1, 0xda, 0x36, 0x09, 0x6e, 0x81, 0xdd, 0x2d, 0xa3, 0x81, 0x4f, 0x82, 0x5b,
	0x65, 0x26, 0x74, 0xb3, 0xf5, 0xea, 0x4e, 0x28, 0x6e, 0x47, 0xb2, 0x0c, 0x12, 0x0e, 0xeb, 0x46,
	0x57, 0x96, 0x5f, 0xc7, 0x64, 0x84, 0xed, 0x3b, 0xa1, 0xb4, 0x8c, 0x0b, 0x96, 0xc2, 0x9a, 0xbb,
	0xe7, 0x83, 0x67, 0x7d, 0x5d, 0x35, 0xe4, 0x95, 0xe5, 0xaf, 0xca, 0x46, 0xbb, 0x78, 0x67, 0xc2,
	0x92, 0x92, 0x0f, 0x2e, 0xf1, 0xc1, 0x13, 0x90, 0x1c, 0xe1, 0x36, 0xe4, 0x14, 0x45, 0xfd, 0xed,
	0x21, 0xf2, 0xeb, 0xa8, 0xd2, 0x43, 0x59, 0x66, 0x5a, 0xd1, 0x2d, 0xa3, 0x9b, 0x68, 0xf4, 0xf1,
	0x71, 0xee, 0xa0, 0xe9, 0xdc, 0x41, 0xbf, 0xe7, 0x0e, 0x7a, 0x58, 0x38, 0xd6, 0x74, 0xe1, 0x58,
	0x3f, 0x17, 0x8e, 0xf5, 0xed, 0xdd, 0xda, 0xff, 0xac, 0x0d, 0x7a, 0x1b, 0x5f, 0x1f, 0xce, 0x3c,
	0x08, 0xda, 0xf0, 0x63, 0x2e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x5f, 0x97, 0x75, 0x58,
	0x04, 0x00, 0x00,
}

func (m *Metricset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metricset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metricset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for iNdEx := len(m.Metrics) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Metrics[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetricset(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.DesinationServiceResource) > 0 {
		i -= len(m.DesinationServiceResource)
		copy(dAtA[i:], m.DesinationServiceResource)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.DesinationServiceResource)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.SpanSubtype) > 0 {
		i -= len(m.SpanSubtype)
		copy(dAtA[i:], m.SpanSubtype)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.SpanSubtype)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.SpanType) > 0 {
		i -= len(m.SpanType)
		copy(dAtA[i:], m.SpanType)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.SpanType)))
		i--
		dAtA[i] = 0x52
	}
	if m.TransactionRoot {
		i--
		if m.TransactionRoot {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.TransactionResult) > 0 {
		i -= len(m.TransactionResult)
		copy(dAtA[i:], m.TransactionResult)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.TransactionResult)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.TransactionType) > 0 {
		i -= len(m.TransactionType)
		copy(dAtA[i:], m.TransactionType)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.TransactionType)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.TransactionName) > 0 {
		i -= len(m.TransactionName)
		copy(dAtA[i:], m.TransactionName)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.TransactionName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EventOutcome) > 0 {
		i -= len(m.EventOutcome)
		copy(dAtA[i:], m.EventOutcome)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.EventOutcome)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TimeseriesId) > 0 {
		i -= len(m.TimeseriesId)
		copy(dAtA[i:], m.TimeseriesId)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.TimeseriesId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintMetricset(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMetricset(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Metric) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metric) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metric) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != nil {
		{
			size := m.Value.Size()
			i -= size
			if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Unit) > 0 {
		i -= len(m.Unit)
		copy(dAtA[i:], m.Unit)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Unit)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Metric_Double) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metric_Double) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Double))))
	i--
	dAtA[i] = 0x21
	return len(dAtA) - i, nil
}
func (m *Metric_Histogram) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metric_Histogram) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Histogram != nil {
		{
			size, err := m.Histogram.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetricset(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *MetricHistogram) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricHistogram) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricHistogram) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Counts) > 0 {
		for iNdEx := len(m.Counts) - 1; iNdEx >= 0; iNdEx-- {
			f4 := math.Float64bits(float64(m.Counts[iNdEx]))
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f4))
		}
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Counts)*8))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			f5 := math.Float64bits(float64(m.Values[iNdEx]))
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f5))
		}
		i = encodeVarintMetricset(dAtA, i, uint64(len(m.Values)*8))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetricset(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetricset(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Metricset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Metadata.Size()
	n += 1 + l + sovMetricset(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovMetricset(uint64(l))
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.TimeseriesId)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.EventOutcome)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.TransactionName)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.TransactionType)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.TransactionResult)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	if m.TransactionRoot {
		n += 2
	}
	l = len(m.SpanType)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.SpanSubtype)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.DesinationServiceResource)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovMetricset(uint64(l))
		}
	}
	return n
}

func (m *Metric) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	l = len(m.Unit)
	if l > 0 {
		n += 1 + l + sovMetricset(uint64(l))
	}
	if m.Value != nil {
		n += m.Value.Size()
	}
	return n
}

func (m *Metric_Double) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *Metric_Histogram) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Histogram != nil {
		l = m.Histogram.Size()
		n += 1 + l + sovMetricset(uint64(l))
	}
	return n
}
func (m *MetricHistogram) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		n += 1 + sovMetricset(uint64(len(m.Values)*8)) + len(m.Values)*8
	}
	if len(m.Counts) > 0 {
		n += 1 + sovMetricset(uint64(len(m.Counts)*8)) + len(m.Counts)*8
	}
	return n
}

func sovMetricset(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetricset(x uint64) (n int) {
	return sovMetricset(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Metricset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metricset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metricset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeseriesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeseriesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventOutcome", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventOutcome = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionResult", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionResult = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionRoot", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TransactionRoot = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpanType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanSubtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpanSubtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DesinationServiceResource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DesinationServiceResource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, &Metric{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetricset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Metric) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metric: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metric: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Double", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Value = &Metric_Double{float64(math.Float64frombits(v))}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Histogram", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MetricHistogram{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &Metric_Histogram{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetricset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricHistogram) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricHistogram: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricHistogram: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.Values = append(m.Values, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetricset
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMetricset
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMetricset
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.Values) == 0 {
					m.Values = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.Values = append(m.Values, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
		case 2:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.Counts = append(m.Counts, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetricset
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMetricset
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMetricset
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.Counts) == 0 {
					m.Counts = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.Counts = append(m.Counts, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Counts", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMetricset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetricset(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetricset
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetricset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetricset
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetricset
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetricset
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetricset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetricset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetricset = fmt.Errorf("proto: unexpected end of group")
)
