// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: apm-server/model/proto/useragent.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserAgent) Reset() {
	*x = UserAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apm_server_model_proto_useragent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgent) ProtoMessage() {}

func (x *UserAgent) ProtoReflect() protoreflect.Message {
	mi := &file_apm_server_model_proto_useragent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgent.ProtoReflect.Descriptor instead.
func (*UserAgent) Descriptor() ([]byte, []int) {
	return file_apm_server_model_proto_useragent_proto_rawDescGZIP(), []int{0}
}

func (x *UserAgent) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *UserAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_apm_server_model_proto_useragent_proto protoreflect.FileDescriptor

var file_apm_server_model_proto_useragent_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x61, 0x70, 0x6d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x3b, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x61,
	0x70, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apm_server_model_proto_useragent_proto_rawDescOnce sync.Once
	file_apm_server_model_proto_useragent_proto_rawDescData = file_apm_server_model_proto_useragent_proto_rawDesc
)

func file_apm_server_model_proto_useragent_proto_rawDescGZIP() []byte {
	file_apm_server_model_proto_useragent_proto_rawDescOnce.Do(func() {
		file_apm_server_model_proto_useragent_proto_rawDescData = protoimpl.X.CompressGZIP(file_apm_server_model_proto_useragent_proto_rawDescData)
	})
	return file_apm_server_model_proto_useragent_proto_rawDescData
}

var file_apm_server_model_proto_useragent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apm_server_model_proto_useragent_proto_goTypes = []interface{}{
	(*UserAgent)(nil), // 0: elastic.apm.model.UserAgent
}
var file_apm_server_model_proto_useragent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apm_server_model_proto_useragent_proto_init() }
func file_apm_server_model_proto_useragent_proto_init() {
	if File_apm_server_model_proto_useragent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apm_server_model_proto_useragent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apm_server_model_proto_useragent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apm_server_model_proto_useragent_proto_goTypes,
		DependencyIndexes: file_apm_server_model_proto_useragent_proto_depIdxs,
		MessageInfos:      file_apm_server_model_proto_useragent_proto_msgTypes,
	}.Build()
	File_apm_server_model_proto_useragent_proto = out.File
	file_apm_server_model_proto_useragent_proto_rawDesc = nil
	file_apm_server_model_proto_useragent_proto_goTypes = nil
	file_apm_server_model_proto_useragent_proto_depIdxs = nil
}
